displayName = "EN"
isoCode = "en"
languageCode = "en"
languageName = "English"
rtl = false
weight = 1

title = "kelset.dev"
# logo = "profile.png"
copyright = "© 2022 Lorenzo Sciandra - All rights reserved. Hosted on [GitHub](https://github.com/kelset/kelset.github.io), deployed with [Netlify](https://www.netlify.com/)."
description = "Lorenzo Sciandra's personal website."

dateFormat = "2 January 2006"

[author]
name = "Lorenzo Sciandra"
bio = "Lorenzo is a Senior Software Engineer at Microsoft. A few years ago he decided to use React Native for a project, and he hasn’t stopped since: he became an Open Source maintainer and releaser for the core project in 2018. He also cares a lot about OSS and mental health, so he tries to be an advocate for sustainability & balance."
headline = "React Native, Microsoft, Open Source and Mental Health"
image = "profile.png"
links = [
  {email = "mailto:notkelset@kelset.dev"},
  {dev = "https://dev.to/kelset"},
  {github = "https://github.com/kelset"},
  {gitlab = "https://gitlab.com/kelset"},
  {hashnode = "https://hashnode.com/@kelset"},
  {keybase = "https://keybase.io/kelset"},
  {linkedin = "https://www.linkedin.com/in/lorenzo-sciandra/"},
  {mastodon = "https://mastodon.online/@kelset"},
  {medium = "https://medium.com/@kelset"},
  {twitter = "https://twitter.com/kelset"},
]
